
package Views;
import Models.PQRS;
import Services.PQRSService;
import javax.swing.JOptionPane;



public class RegistroPQRS extends javax.swing.JFrame {
    
    private PQRSService pqrsService; 
    
    /**
     * Creates new form JframeRol
     */
    public RegistroPQRS() {
        initComponents();
        pqrsService =new PQRSService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblcomentario = new javax.swing.JLabel();
        txtcomentario = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        lbltipo = new javax.swing.JLabel();
        txttipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro PQRS");

        lblcomentario.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lblcomentario.setForeground(new java.awt.Color(255, 255, 255));
        lblcomentario.setText("Comentario:");

        txtcomentario.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Guardar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lbltipo.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lbltipo.setForeground(new java.awt.Color(255, 255, 255));
        lbltipo.setText("tipo:");

        txttipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "peticion", "Queja", "Reclamo", "Sugerencia" }));
        txttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcomentario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcomentario)
                            .addComponent(lbltipo)
                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(lbltipo)
                .addGap(18, 18, 18)
                .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblcomentario)
                .addGap(18, 18, 18)
                .addComponent(txtcomentario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // Obtener valores del formulario
        String tipo = txttipo.getSelectedItem().toString();
        String comentario = txtcomentario.getText().trim();
        
        // Validaciones básicas
        if (tipo.equals("Seleccione...")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de PQRS", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (comentario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El comentario no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Crear objeto PQRS (asumiendo que el ID de persona es fijo por ahora)
            // En una aplicación real, obtendrías este ID de la sesión del usuario
            int idPersona = 1; // Valor temporal, deberías obtenerlo del usuario logueado
            
            PQRS nuevoPQRS = new PQRS(idPersona, comentario, idPersona, idPersona, comentario);
            nuevoPQRS.setTipoComentario(tipo);
            nuevoPQRS.setComentario(comentario);
            nuevoPQRS.setIdPersona(idPersona);
            
            // Registrar el PQRS
            pqrsService.Registrarpqrs(nuevoPQRS);
            
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "PQRS registrado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar formulario
            txttipo.setSelectedIndex(0);
            txtcomentario.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar PQRS: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
                                     

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPQRS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcomentario;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JTextField txtcomentario;
    private javax.swing.JComboBox<String> txttipo;
    // End of variables declaration//GEN-END:variables
} 
